interface JobPostingSeed {
	title: string;
	content: string;
	metadata: {
		careerGoal: string;
		company: string;
		seniority: string;
		requiredSkills: string[];
		niceToHaveSkills: string[];
		salary: string;
		location: string;
	};
}

export const jobPostings: JobPostingSeed[] = [
	// ===== AI / Machine Learning Engineer =====
	{ title: "ML Engineer at Swiggy", content: "Build ML models for food recommendation, delivery time prediction, and demand forecasting. Work with terabytes of order data to optimize logistics across 500+ cities.", metadata: { careerGoal: "AI / Machine Learning Engineer", company: "Swiggy", seniority: "mid", requiredSkills: ["Python", "Machine Learning", "Deep Learning", "TensorFlow", "PyTorch", "SQL", "Statistics"], niceToHaveSkills: ["CUDA", "Kubernetes", "MLflow", "Spark", "Docker"], salary: "₹18-30 LPA", location: "Bengaluru" } },
	{ title: "ML Engineer at Razorpay", content: "Build ML models for fraud detection, credit risk scoring, and payment optimization. Process real-time transaction data to identify patterns and prevent fraud.", metadata: { careerGoal: "AI / Machine Learning Engineer", company: "Razorpay", seniority: "mid", requiredSkills: ["Python", "Machine Learning", "Scikit-learn", "Statistics", "SQL", "Model Evaluation", "Feature Engineering"], niceToHaveSkills: ["PyTorch", "Spark", "Kubernetes", "Docker", "MLflow"], salary: "₹20-35 LPA", location: "Bengaluru" } },
	{ title: "AI Engineer at Zomato", content: "Build recommendation systems for restaurant discovery and food delivery. Apply NLP for search and personalization. Strong PyTorch and ML fundamentals required.", metadata: { careerGoal: "AI / Machine Learning Engineer", company: "Zomato", seniority: "senior", requiredSkills: ["Python", "Machine Learning", "PyTorch", "Deep Learning", "NLP", "Statistics", "Feature Engineering"], niceToHaveSkills: ["CUDA", "Spark", "Kubernetes", "TensorFlow", "Docker"], salary: "₹30-50 LPA", location: "Gurugram" } },
	{ title: "Junior ML Engineer at Fractal Analytics", content: "Join the AI team building ML solutions for Fortune 500 clients. Work on data preprocessing, model training, and deployment under senior mentorship.", metadata: { careerGoal: "AI / Machine Learning Engineer", company: "Fractal Analytics", seniority: "junior", requiredSkills: ["Python", "Machine Learning", "SQL", "Statistics", "Data Preprocessing", "Pandas", "NumPy"], niceToHaveSkills: ["TensorFlow", "PyTorch", "Scikit-learn", "MLflow", "Docker"], salary: "₹6-10 LPA", location: "Mumbai" } },
	{ title: "Computer Vision Engineer at Ola", content: "Build computer vision models for autonomous driving and driver safety monitoring. Work on object detection, lane detection, and real-time video processing.", metadata: { careerGoal: "AI / Machine Learning Engineer", company: "Ola", seniority: "senior", requiredSkills: ["Python", "Deep Learning", "Computer Vision", "PyTorch", "CUDA", "Model Evaluation", "C++"], niceToHaveSkills: ["TensorFlow", "ONNX", "Docker", "Kubernetes", "ROS"], salary: "₹35-55 LPA", location: "Bengaluru" } },
	{ title: "ML Scientist at TCS Research", content: "Research and develop novel ML algorithms for enterprise AI solutions. Publish papers and build prototypes for real-world business problems.", metadata: { careerGoal: "AI / Machine Learning Engineer", company: "TCS", seniority: "mid", requiredSkills: ["Python", "Machine Learning", "Statistics", "Linear Algebra", "Research", "TensorFlow", "PyTorch"], niceToHaveSkills: ["CUDA", "Distributed Training", "MLflow", "Kubernetes", "Spark"], salary: "₹12-22 LPA", location: "Pune" } },

	// ===== Frontend Engineer =====
	{ title: "Frontend Engineer at Flipkart", content: "Build the UI for India's largest e-commerce platform. Work on React-based micro-frontends, web performance optimization, and mobile-first responsive design.", metadata: { careerGoal: "Frontend Engineer", company: "Flipkart", seniority: "mid", requiredSkills: ["JavaScript", "TypeScript", "React", "CSS", "HTML", "Web Performance", "Responsive Design"], niceToHaveSkills: ["Next.js", "Tailwind CSS", "Jest", "Storybook", "Figma"], salary: "₹15-28 LPA", location: "Bengaluru" } },
	{ title: "Senior Frontend Engineer at CRED", content: "Build premium UI experiences for credit-card users. Work on complex animations, micro-interactions, and pixel-perfect implementations with React and TypeScript.", metadata: { careerGoal: "Frontend Engineer", company: "CRED", seniority: "senior", requiredSkills: ["TypeScript", "React", "CSS", "Web Performance", "HTML", "Accessibility", "System Design"], niceToHaveSkills: ["Next.js", "Storybook", "Figma", "Webpack", "Node.js"], salary: "₹30-50 LPA", location: "Bengaluru" } },
	{ title: "Frontend Developer at Meesho", content: "Build the UI for India's social commerce platform. Work on WebView optimization, PWA implementation, and performant web experiences for tier-2/3 city users.", metadata: { careerGoal: "Frontend Engineer", company: "Meesho", seniority: "mid", requiredSkills: ["JavaScript", "React", "TypeScript", "CSS", "HTML", "Web Performance", "Responsive Design"], niceToHaveSkills: ["Next.js", "Jest", "Figma", "Tailwind CSS", "PWA"], salary: "₹12-22 LPA", location: "Bengaluru" } },
	{ title: "Junior Frontend Developer at Unacademy", content: "Build interactive learning experiences. Work with senior engineers on component development, design system integration, and accessibility improvements.", metadata: { careerGoal: "Frontend Engineer", company: "Unacademy", seniority: "junior", requiredSkills: ["JavaScript", "React", "TypeScript", "CSS", "HTML", "Responsive Design"], niceToHaveSkills: ["Next.js", "Tailwind CSS", "Jest", "Figma", "Storybook"], salary: "₹5-10 LPA", location: "Bengaluru" } },
	{ title: "Frontend Engineer at Groww", content: "Build the investment platform UI. Work on real-time stock data visualization, portfolio dashboards, and seamless transaction flows with React and TypeScript.", metadata: { careerGoal: "Frontend Engineer", company: "Groww", seniority: "mid", requiredSkills: ["TypeScript", "React", "JavaScript", "CSS", "HTML", "Responsive Design", "Web Performance"], niceToHaveSkills: ["Next.js", "Tailwind CSS", "Jest", "Storybook", "Figma"], salary: "₹14-26 LPA", location: "Bengaluru" } },
	{ title: "Frontend Infrastructure Engineer at Zomato", content: "Build the frontend platform powering Zomato's customer and partner apps. Focus on build tooling, component libraries, performance monitoring, and developer experience.", metadata: { careerGoal: "Frontend Engineer", company: "Zomato", seniority: "senior", requiredSkills: ["TypeScript", "React", "CSS", "Web Performance", "Build Tools", "HTML", "Accessibility"], niceToHaveSkills: ["Next.js", "Webpack", "Storybook", "Figma", "Node.js"], salary: "₹28-48 LPA", location: "Gurugram" } },

	// ===== Backend Engineer =====
	{ title: "Backend Engineer at Razorpay", content: "Build scalable payment infrastructure processing billions in transactions. Design APIs, optimize database queries, and build reliable financial systems.", metadata: { careerGoal: "Backend Engineer", company: "Razorpay", seniority: "senior", requiredSkills: ["REST APIs", "SQL", "System Design", "Database Design", "Performance Optimization", "Testing", "Python"], niceToHaveSkills: ["Go", "Kafka", "Redis", "Docker", "Kubernetes", "Distributed Systems"], salary: "₹30-50 LPA", location: "Bengaluru" } },
	{ title: "Backend Engineer at Zerodha", content: "Build the backend for India's largest stockbroker. Handle high-throughput trading systems, low-latency APIs, and real-time market data processing.", metadata: { careerGoal: "Backend Engineer", company: "Zerodha", seniority: "mid", requiredSkills: ["REST APIs", "SQL", "System Design", "Python", "Database Design", "Performance Optimization"], niceToHaveSkills: ["Go", "Redis", "Kafka", "Docker", "Kubernetes", "Testing"], salary: "₹18-32 LPA", location: "Bengaluru" } },
	{ title: "Backend Developer at Niyo", content: "Build banking APIs and financial services platform. Work on account aggregation, payment processing, and transaction systems with Node.js and PostgreSQL.", metadata: { careerGoal: "Backend Engineer", company: "Niyo", seniority: "mid", requiredSkills: ["REST APIs", "SQL", "Node.js", "Database Design", "System Design", "Testing", "API Design"], niceToHaveSkills: ["TypeScript", "Redis", "Docker", "Kafka", "Kubernetes"], salary: "₹12-24 LPA", location: "Bengaluru" } },
	{ title: "Junior Backend Engineer at Upstox", content: "Build APIs for the trading platform. Work on feature development, database queries, and API optimization under senior engineer mentorship.", metadata: { careerGoal: "Backend Engineer", company: "Upstox", seniority: "junior", requiredSkills: ["REST APIs", "SQL", "Python", "Java", "Testing", "System Design Basics", "Git"], niceToHaveSkills: ["Redis", "Docker", "Kafka", "PostgreSQL", "API Design"], salary: "₹6-12 LPA", location: "Mumbai" } },
	{ title: "Backend Engineer at Ola", content: "Build the backend for ride-hailing and electric vehicle platforms. Handle real-time location tracking, pricing algorithms, and fleet management systems.", metadata: { careerGoal: "Backend Engineer", company: "Ola", seniority: "mid", requiredSkills: ["REST APIs", "SQL", "System Design", "API Design", "Database Design", "Performance Optimization", "Java"], niceToHaveSkills: ["Go", "Kafka", "Redis", "Docker", "Kubernetes", "Distributed Systems"], salary: "₹15-28 LPA", location: "Bengaluru" } },
	{ title: "Backend Engineer at Infosys (Digital)", content: "Build enterprise backend systems for global clients. Work on microservices architecture, cloud-native development, and API design using Java and Spring Boot.", metadata: { careerGoal: "Backend Engineer", company: "Infosys", seniority: "mid", requiredSkills: ["Java", "REST APIs", "SQL", "Spring Boot", "System Design", "Testing", "Git"], niceToHaveSkills: ["Docker", "Kubernetes", "AWS", "Kafka", "Redis", "Microservices"], salary: "₹8-15 LPA", location: "Mysuru" } },

	// ===== Full-Stack Developer =====
	{ title: "Full-Stack Developer at Freshworks", content: "Build SaaS products for global customers. Work across React frontend and Ruby/Node.js backend. Own features end-to-end from UI to database.", metadata: { careerGoal: "Full-Stack Developer", company: "Freshworks", seniority: "mid", requiredSkills: ["TypeScript", "React", "Node.js", "SQL", "REST APIs", "PostgreSQL", "Git"], niceToHaveSkills: ["Ruby", "Docker", "Redis", "AWS", "Testing", "System Design Basics"], salary: "₹14-26 LPA", location: "Chennai" } },
	{ title: "Full-Stack Developer at Chargebee", content: "Build subscription management platform. Work across React frontend and Ruby/Rails backend. Handle billing workflows and payment integrations.", metadata: { careerGoal: "Full-Stack Developer", company: "Chargebee", seniority: "mid", requiredSkills: ["TypeScript", "React", "Ruby", "REST APIs", "SQL", "PostgreSQL", "Git"], niceToHaveSkills: ["Rails", "Docker", "Redis", "AWS", "Testing", "System Design"], salary: "₹15-28 LPA", location: "Chennai" } },
	{ title: "Full-Stack Developer at MyGate", content: "Build the community management platform. Work on React frontend and Node.js backend for India's largest apartment management app.", metadata: { careerGoal: "Full-Stack Developer", company: "MyGate", seniority: "mid", requiredSkills: ["JavaScript", "TypeScript", "React", "Node.js", "REST APIs", "SQL", "MySQL", "Git"], niceToHaveSkills: ["Docker", "Redis", "AWS", "Testing", "System Design Basics"], salary: "₹12-22 LPA", location: "Bengaluru" } },
	{ title: "Junior Full-Stack Developer at Innovaccer", content: "Build healthcare SaaS products. Work on features across the stack with mentorship from senior engineers. Learn React, Node.js, and database design.", metadata: { careerGoal: "Full-Stack Developer", company: "Innovaccer", seniority: "junior", requiredSkills: ["JavaScript", "React", "Node.js", "SQL", "REST APIs", "Git", "HTML/CSS"], niceToHaveSkills: ["TypeScript", "Docker", "PostgreSQL", "Testing", "Redis"], salary: "₹5-10 LPA", location: "Noida" } },
	{ title: "Senior Full-Stack at BrowserStack", content: "Build the cloud testing platform. Design and implement features spanning React frontend and Go/Node.js backend. Mentor junior engineers.", metadata: { careerGoal: "Full-Stack Developer", company: "BrowserStack", seniority: "senior", requiredSkills: ["TypeScript", "React", "Node.js", "SQL", "System Design", "Go", "REST APIs"], niceToHaveSkills: ["Docker", "Redis", "Kubernetes", "AWS", "Testing", "Performance Optimization"], salary: "₹28-48 LPA", location: "Mumbai" } },
	{ title: "Full-Stack Developer at Tata Digital", content: "Build the super-app platform for Tata group. Work across React Native frontend and Java/Node.js backend for e-commerce, financial services, and loyalty programs.", metadata: { careerGoal: "Full-Stack Developer", company: "Tata Digital", seniority: "mid", requiredSkills: ["JavaScript", "React", "Node.js", "Java", "REST APIs", "SQL", "Git"], niceToHaveSkills: ["React Native", "Docker", "AWS", "Redis", "Kafka", "Testing"], salary: "₹12-24 LPA", location: "Mumbai" } },

	// ===== Cloud Engineer =====
	{ title: "Cloud Engineer at AWS India", content: "Help Indian customers architect and migrate to AWS. Design cloud-native solutions using EC2, S3, Lambda, and EKS for enterprises and startups.", metadata: { careerGoal: "Cloud Engineer (AWS / Azure / GCP)", company: "AWS India", seniority: "mid", requiredSkills: ["AWS", "Cloud Architecture", "Networking", "Linux", "Infrastructure as Code", "Security Best Practices", "Terraform"], niceToHaveSkills: ["Kubernetes", "Docker", "CI/CD", "Cost Optimization", "Python", "Monitoring"], salary: "₹18-35 LPA", location: "Bengaluru" } },
	{ title: "Cloud Architect at Google Cloud India", content: "Design GCP infrastructure for Indian enterprises. Work on migrations, landing zones, and architecture reviews for large-scale deployments.", metadata: { careerGoal: "Cloud Engineer (AWS / Azure / GCP)", company: "Google Cloud India", seniority: "senior", requiredSkills: ["GCP", "Cloud Architecture", "Networking", "Linux", "Security Best Practices", "Infrastructure as Code", "Terraform"], niceToHaveSkills: ["AWS", "Azure", "Kubernetes", "CI/CD", "Cost Optimization", "Python"], salary: "₹35-60 LPA", location: "Bengaluru" } },
	{ title: "Cloud Engineer at HCL CloudSMART", content: "Build and manage cloud infrastructure for enterprise clients. Work on multi-cloud automation, migration projects, and cloud operations.", metadata: { careerGoal: "Cloud Engineer (AWS / Azure / GCP)", company: "HCL Technologies", seniority: "mid", requiredSkills: ["AWS", "Azure", "Cloud Architecture", "Linux", "Infrastructure as Code", "Networking", "Terraform"], niceToHaveSkills: ["GCP", "Docker", "Kubernetes", "CI/CD", "Python", "Monitoring"], salary: "₹8-16 LPA", location: "Noida" } },
	{ title: "Junior Cloud Engineer at DigitalOcean India", content: "Help build and maintain cloud infrastructure. Learn from senior engineers while working on networking, storage, and cloud operations.", metadata: { careerGoal: "Cloud Engineer (AWS / Azure / GCP)", company: "DigitalOcean India", seniority: "junior", requiredSkills: ["Linux", "Networking", "Cloud Architecture Basics", "Infrastructure as Code", "Security Basics"], niceToHaveSkills: ["AWS", "Terraform", "Docker", "Kubernetes", "CI/CD", "Python"], salary: "₹5-9 LPA", location: "Bengaluru" } },
	{ title: "Multi-Cloud Engineer at Wipro", content: "Design multi-cloud infrastructure for global clients. Work across AWS, Azure, and GCP with Terraform and automation tooling.", metadata: { careerGoal: "Cloud Engineer (AWS / Azure / GCP)", company: "Wipro", seniority: "mid", requiredSkills: ["AWS", "Azure", "GCP", "Terraform", "Cloud Architecture", "Networking", "Linux"], niceToHaveSkills: ["Kubernetes", "Docker", "CI/CD", "Python", "Security Best Practices", "Cost Optimization"], salary: "₹8-16 LPA", location: "Hyderabad" } },
	{ title: "Cloud Solutions Architect at LTIMindtree", content: "Design cloud solutions for enterprise digital transformation. Create architecture blueprints, migration plans, and cloud governance frameworks.", metadata: { careerGoal: "Cloud Engineer (AWS / Azure / GCP)", company: "LTIMindtree", seniority: "senior", requiredSkills: ["AWS", "Cloud Architecture", "Solution Design", "Security Best Practices", "Networking", "Terraform", "Cost Optimization"], niceToHaveSkills: ["Azure", "GCP", "Kubernetes", "DevOps", "Python", "TOGAF"], salary: "₹20-38 LPA", location: "Mumbai" } },

	// ===== DevOps / Platform Engineer =====
	{ title: "DevOps Engineer at Razorpay", content: "Build and maintain CI/CD infrastructure for payment platforms. Work on Kubernetes clusters, Terraform modules, and developer tooling at scale.", metadata: { careerGoal: "DevOps / Platform Engineer", company: "Razorpay", seniority: "mid", requiredSkills: ["CI/CD", "Docker", "Kubernetes", "Linux", "Scripting", "Terraform", "Monitoring"], niceToHaveSkills: ["Go", "Prometheus", "Grafana", "Helm", "GitHub Actions", "Ansible"], salary: "₹20-35 LPA", location: "Bengaluru" } },
	{ title: "Platform Engineer at Zerodha", content: "Build the internal developer platform for India's largest stockbroker. Create tooling for deployment, observability, and infrastructure automation.", metadata: { careerGoal: "DevOps / Platform Engineer", company: "Zerodha", seniority: "senior", requiredSkills: ["Kubernetes", "Docker", "CI/CD", "Linux", "Go", "Terraform", "Monitoring"], niceToHaveSkills: ["Prometheus", "Grafana", "Helm", "Python", "Service Mesh", "Distributed Systems"], salary: "₹30-50 LPA", location: "Bengaluru" } },
	{ title: "DevOps Engineer at Swiggy", content: "Build the deployment infrastructure for India's largest food delivery platform. Work on canary deployments, auto-scaling, and reliability at scale.", metadata: { careerGoal: "DevOps / Platform Engineer", company: "Swiggy", seniority: "mid", requiredSkills: ["CI/CD", "Kubernetes", "Docker", "Linux", "Terraform", "Monitoring", "Scripting"], niceToHaveSkills: ["Prometheus", "Grafana", "Go", "Helm", "Python", "Reliability Engineering"], salary: "₹18-32 LPA", location: "Bengaluru" } },
	{ title: "Junior DevOps Engineer at Postman", content: "Join the platform team. Help maintain CI/CD infrastructure, learn container orchestration, and automate operational tasks with mentorship.", metadata: { careerGoal: "DevOps / Platform Engineer", company: "Postman", seniority: "junior", requiredSkills: ["Linux", "Docker", "Scripting", "CI/CD", "Git", "Basic Monitoring"], niceToHaveSkills: ["Kubernetes", "Terraform", "Prometheus", "Grafana", "Python", "Ansible"], salary: "₹6-12 LPA", location: "Bengaluru" } },
	{ title: "Platform Engineer at Flipkart", content: "Build the platform powering India's largest e-commerce engine. Work on Kubernetes infrastructure, service mesh, and developer workflow automation.", metadata: { careerGoal: "DevOps / Platform Engineer", company: "Flipkart", seniority: "senior", requiredSkills: ["Kubernetes", "Docker", "CI/CD", "Linux", "Terraform", "System Design", "Monitoring"], niceToHaveSkills: ["Go", "Prometheus", "Grafana", "Service Mesh", "Helm", "Python"], salary: "₹30-50 LPA", location: "Bengaluru" } },
	{ title: "DevOps Engineer at Tech Mahindra", content: "Build DevOps pipelines for telecom and enterprise clients. Work on automation, cloud migration, and CI/CD implementation for large-scale projects.", metadata: { careerGoal: "DevOps / Platform Engineer", company: "Tech Mahindra", seniority: "mid", requiredSkills: ["CI/CD", "Docker", "Linux", "Scripting", "Terraform", "Jenkins", "Git"], niceToHaveSkills: ["Kubernetes", "Ansible", "Prometheus", "Grafana", "AWS", "Python"], salary: "₹7-14 LPA", location: "Pune" } },

	// ===== Software Engineer (Product-Based Companies) =====
	{ title: "SDE at Google India", content: "Build products for billions of users. Strong DSA and system design required. Work on search, Android, payments, or cloud products from India.", metadata: { careerGoal: "Software Engineer (Product-Based Companies)", company: "Google India", seniority: "mid", requiredSkills: ["Data Structures", "Algorithms", "System Design", "Object-Oriented Programming", "Testing", "API Design", "Python"], niceToHaveSkills: ["Java", "C++", "Distributed Systems", "SQL", "Docker", "Performance Optimization"], salary: "₹30-60 LPA", location: "Bengaluru" } },
	{ title: "SDE at Amazon India", content: "Build e-commerce, payments, and AWS solutions. Ownership-driven culture. Strong DSA and system design required for interviews.", metadata: { careerGoal: "Software Engineer (Product-Based Companies)", company: "Amazon India", seniority: "mid", requiredSkills: ["Data Structures", "Algorithms", "System Design", "Object-Oriented Programming", "Testing", "API Design", "Java"], niceToHaveSkills: ["AWS", "SQL", "Docker", "Distributed Systems", "Kafka", "Performance Optimization"], salary: "₹25-50 LPA", location: "Bengaluru" } },
	{ title: "SDE at Microsoft India", content: "Build Azure, Office 365, and developer tools. Large-scale systems with C# and .NET. Focus on engineering excellence and product impact.", metadata: { careerGoal: "Software Engineer (Product-Based Companies)", company: "Microsoft India", seniority: "mid", requiredSkills: ["Data Structures", "Algorithms", "System Design", "Object-Oriented Programming", "Testing", "C#", "API Design"], niceToHaveSkills: ["Azure", "SQL", "Docker", "Performance Optimization", "Distributed Systems", ".NET"], salary: "₹25-55 LPA", location: "Hyderabad" } },
	{ title: "SDE at Flipkart", content: "Build India's leading e-commerce platform. Work on search, recommendations, payments, and supply chain at massive scale.", metadata: { careerGoal: "Software Engineer (Product-Based Companies)", company: "Flipkart", seniority: "mid", requiredSkills: ["Data Structures", "Algorithms", "System Design", "Object-Oriented Programming", "Testing", "Java", "API Design"], niceToHaveSkills: ["SQL", "Docker", "Kafka", "Redis", "Performance Optimization", "Distributed Systems"], salary: "₹20-40 LPA", location: "Bengaluru" } },
	{ title: "SDE (New Grad) at Flipkart", content: "Join the Flipkart Graduate Program. Rotate through teams and build foundational engineering skills. Strong DSA and problem-solving required.", metadata: { careerGoal: "Software Engineer (Product-Based Companies)", company: "Flipkart", seniority: "junior", requiredSkills: ["Data Structures", "Algorithms", "Object-Oriented Programming", "Testing", "System Design Basics", "Java", "Git"], niceToHaveSkills: ["Python", "SQL", "Docker", "API Design", "Kafka"], salary: "₹12-20 LPA", location: "Bengaluru" } },
	{ title: "SDE at Ola", content: "Build the mobility platform serving millions. Work on ride-hailing, electric vehicles, and financial services product engineering.", metadata: { careerGoal: "Software Engineer (Product-Based Companies)", company: "Ola", seniority: "senior", requiredSkills: ["Data Structures", "Algorithms", "System Design", "Distributed Systems", "Java", "Testing", "API Design"], niceToHaveSkills: ["Python", "Go", "Docker", "Kubernetes", "SQL", "Performance Optimization"], salary: "₹35-60 LPA", location: "Bengaluru" } },

	// ===== Data Analyst =====
	{ title: "Data Analyst at Flipkart", content: "Analyze marketplace dynamics, pricing trends, and seller performance. Build dashboards, run SQL queries on petabytes of data, and present insights to product teams.", metadata: { careerGoal: "Data Analyst", company: "Flipkart", seniority: "mid", requiredSkills: ["SQL", "Statistics", "Data Visualization", "Python", "Tableau", "Excel", "Business Acumen"], niceToHaveSkills: ["Power BI", "Looker", "R", "A/B Testing", "Airflow"], salary: "₹10-20 LPA", location: "Bengaluru" } },
	{ title: "Data Analyst at Swiggy", content: "Analyze food ordering patterns, delivery efficiency, and customer behavior. Drive business decisions with data-driven insights and actionable recommendations.", metadata: { careerGoal: "Data Analyst", company: "Swiggy", seniority: "mid", requiredSkills: ["SQL", "Statistics", "Data Visualization", "Python", "Excel", "A/B Testing", "Business Acumen"], niceToHaveSkills: ["Tableau", "Power BI", "R", "Looker", "Airflow"], salary: "₹10-20 LPA", location: "Bengaluru" } },
	{ title: "Junior Data Analyst at Zomato", content: "Support the analytics team with reporting, dashboard maintenance, and ad-hoc analysis. Learn from senior analysts while working on real business problems.", metadata: { careerGoal: "Data Analyst", company: "Zomato", seniority: "junior", requiredSkills: ["SQL", "Statistics", "Data Visualization", "Excel", "Python Basics", "Business Acumen"], niceToHaveSkills: ["Python", "Tableau", "Power BI", "R", "A/B Testing"], salary: "₹4-8 LPA", location: "Gurugram" } },
	{ title: "Senior Data Analyst at Ola", content: "Drive mobility analytics, analyze supply-demand dynamics. Build real-time dashboards, design experiments, and present to leadership.", metadata: { careerGoal: "Data Analyst", company: "Ola", seniority: "senior", requiredSkills: ["SQL", "Statistics", "Python", "Data Visualization", "A/B Testing", "Experimental Design", "Business Acumen"], niceToHaveSkills: ["Tableau", "R", "Spark", "Airflow", "Looker"], salary: "₹20-35 LPA", location: "Bengaluru" } },
	{ title: "Business Analyst at TCS", content: "Analyze business requirements, create data reports, and support decision-making for enterprise clients. Work with SQL, Excel, and visualization tools.", metadata: { careerGoal: "Data Analyst", company: "TCS", seniority: "junior", requiredSkills: ["SQL", "Excel", "Data Visualization", "Statistics", "Business Acumen", "Communication"], niceToHaveSkills: ["Python", "Tableau", "Power BI", "R"], salary: "₹3.5-6 LPA", location: "Mumbai" } },
	{ title: "Data Analyst at Groww", content: "Analyze investment patterns, user behavior, and portfolio performance. Build analytics dashboards and drive product decisions with data.", metadata: { careerGoal: "Data Analyst", company: "Groww", seniority: "mid", requiredSkills: ["SQL", "Python", "Statistics", "Data Visualization", "A/B Testing", "Excel", "Business Acumen"], niceToHaveSkills: ["Tableau", "Looker", "R", "Spark", "Airflow"], salary: "₹12-24 LPA", location: "Bengaluru" } },

	// ===== Data Engineer =====
	{ title: "Data Engineer at Swiggy", content: "Build data pipelines processing terabytes of order data. Design real-time streaming systems for tracking and analytics. Work with Spark, Airflow, and Kafka.", metadata: { careerGoal: "Data Engineer", company: "Swiggy", seniority: "mid", requiredSkills: ["SQL", "Python", "ETL/ELT", "Apache Spark", "Airflow", "Data Modeling", "Kafka"], niceToHaveSkills: ["dbt", "Snowflake", "BigQuery", "Docker", "Kubernetes", "Data Warehousing"], salary: "₹15-28 LPA", location: "Bengaluru" } },
	{ title: "Data Engineer at Razorpay", content: "Build financial data pipelines processing millions of transactions. Design reliable ETL workflows and maintain data quality for analytics and ML.", metadata: { careerGoal: "Data Engineer", company: "Razorpay", seniority: "senior", requiredSkills: ["SQL", "Python", "ETL/ELT", "Apache Spark", "Kafka", "Data Modeling", "Data Warehousing"], niceToHaveSkills: ["Airflow", "dbt", "Kubernetes", "Go", "Snowflake", "Data Quality"], salary: "₹25-45 LPA", location: "Bengaluru" } },
	{ title: "Data Engineer at Groww", content: "Build data infrastructure for the investment platform. Manage data pipelines for stock market data, user analytics, and financial reporting.", metadata: { careerGoal: "Data Engineer", company: "Groww", seniority: "mid", requiredSkills: ["SQL", "Python", "ETL/ELT", "Apache Spark", "Airflow", "Data Modeling", "Data Warehousing"], niceToHaveSkills: ["Kafka", "dbt", "Snowflake", "BigQuery", "Docker", "Kubernetes"], salary: "₹14-28 LPA", location: "Bengaluru" } },
	{ title: "Junior Data Engineer at Fractal Analytics", content: "Join the data engineering team building client data solutions. Learn modern data stack tools and work with experienced engineers on real projects.", metadata: { careerGoal: "Data Engineer", company: "Fractal Analytics", seniority: "junior", requiredSkills: ["SQL", "Python", "ETL/ELT", "Data Modeling", "Data Warehousing", "Git"], niceToHaveSkills: ["Apache Spark", "Airflow", "dbt", "Docker", "Kafka", "Snowflake"], salary: "₹5-10 LPA", location: "Mumbai" } },
	{ title: "Data Engineer at Zomato", content: "Build data pipelines for restaurant analytics, delivery tracking, and customer insights. Manage big data infrastructure with Spark and real-time streaming.", metadata: { careerGoal: "Data Engineer", company: "Zomato", seniority: "mid", requiredSkills: ["SQL", "Python", "ETL/ELT", "Apache Spark", "Kafka", "Airflow", "Data Warehousing"], niceToHaveSkills: ["Scala", "dbt", "Snowflake", "BigQuery", "Kubernetes", "Docker"], salary: "₹15-28 LPA", location: "Gurugram" } },
	{ title: "Data Infrastructure Engineer at Flipkart", content: "Build and maintain data infrastructure for India's largest e-commerce platform. Design data storage, processing, and access patterns at petabyte scale.", metadata: { careerGoal: "Data Engineer", company: "Flipkart", seniority: "senior", requiredSkills: ["SQL", "Spark", "Hadoop", "Python", "Data Warehousing", "Kafka", "Airflow"], niceToHaveSkills: ["Java", "Flink", "Iceberg", "Kubernetes", "dbt", "Snowflake"], salary: "₹28-50 LPA", location: "Bengaluru" } },

	// ===== Cybersecurity Specialist =====
	{ title: "Security Engineer at Razorpay", content: "Protect payment infrastructure from fraud and attacks. Build security controls, monitor threats, and respond to incidents in real-time.", metadata: { careerGoal: "Cybersecurity Specialist", company: "Razorpay", seniority: "mid", requiredSkills: ["Network Security", "Threat Analysis", "Incident Response", "Application Security", "Linux", "Python", "Cryptography Basics"], niceToHaveSkills: ["SIEM", "Burp Suite", "Wireshark", "Penetration Testing", "Cloud Security", "Splunk"], salary: "₹15-30 LPA", location: "Bengaluru" } },
	{ title: "Security Analyst at Wipro", content: "Monitor and analyze security events for global clients. Work on SIEM, incident triage, and security operations center (SOC) operations.", metadata: { careerGoal: "Cybersecurity Specialist", company: "Wipro", seniority: "junior", requiredSkills: ["Network Security", "SIEM", "Threat Analysis", "Incident Response", "Linux", "Security Policies"], niceToHaveSkills: ["Splunk", "Wireshark", "Nmap", "Python", "Scripting", "Compliance"], salary: "₹4-8 LPA", location: "Hyderabad" } },
	{ title: "Application Security Engineer at Flipkart", content: "Secure Flipkart's e-commerce platform. Conduct security reviews, build security automation, and mentor developers on secure coding.", metadata: { careerGoal: "Cybersecurity Specialist", company: "Flipkart", seniority: "mid", requiredSkills: ["Network Security", "Application Security", "Threat Analysis", "Vulnerability Assessment", "Python", "Web Security", "Cryptography"], niceToHaveSkills: ["Burp Suite", "Docker", "Kubernetes", "CI/CD Security", "Cloud Security"], salary: "₹18-32 LPA", location: "Bengaluru" } },
	{ title: "Penetration Tester at Lucideus (now Safe Security)", content: "Conduct penetration tests and vulnerability assessments for enterprise clients. Write detailed security reports and recommend remediation.", metadata: { careerGoal: "Cybersecurity Specialist", company: "Safe Security", seniority: "mid", requiredSkills: ["Network Security", "Penetration Testing", "Vulnerability Assessment", "Web Security", "Linux", "Scripting", "Burp Suite"], niceToHaveSkills: ["Metasploit", "Kali Linux", "Nmap", "Wireshark", "Cloud Security", "Python"], salary: "₹8-18 LPA", location: "Mumbai" } },
	{ title: "CISO at Indian Startup", content: "Lead security strategy for a fast-growing Indian startup. Build security programs, ensure compliance, and manage risk for cloud-native infrastructure.", metadata: { careerGoal: "Cybersecurity Specialist", company: "Indian Startup", seniority: "senior", requiredSkills: ["Risk Management", "Security Policies", "Incident Response", "Compliance", "Cloud Security", "Network Security", "Leadership"], niceToHaveSkills: ["AWS Security", "Kubernetes Security", "SIEM", "Cryptography", "Penetration Testing", "ISO 27001"], salary: "₹35-65 LPA", location: "Bengaluru" } },
	{ title: "SOC Analyst at TCS", content: "Monitor security events, triage alerts, and respond to incidents in TCS's global SOC. Work with SIEM tools and follow incident response playbooks.", metadata: { careerGoal: "Cybersecurity Specialist", company: "TCS", seniority: "junior", requiredSkills: ["Network Security", "Security Monitoring", "Incident Response", "Linux", "Security Policies", "Communication"], niceToHaveSkills: ["SIEM", "Splunk", "Wireshark", "Nmap", "Python", "Certifications"], salary: "₹3.5-6 LPA", location: "Kolkata" } },

	// ===== Mobile Developer =====
	{ title: "Android Engineer at Flipkart", content: "Build the Android app for India's largest e-commerce platform. Work on Jetpack Compose, performance optimization, and features for millions of users.", metadata: { careerGoal: "Mobile Developer", company: "Flipkart", seniority: "mid", requiredSkills: ["Kotlin", "Android", "Jetpack Compose", "REST APIs", "Git", "App Architecture", "Material Design"], niceToHaveSkills: ["Swift", "Flutter", "GraphQL", "Java", "Testing", "Play Store"], salary: "₹16-30 LPA", location: "Bengaluru" } },
	{ title: "iOS Engineer at Swiggy", content: "Build the Swiggy iOS app used by millions. Work on SwiftUI, performance optimization, and features for food delivery and instant commerce.", metadata: { careerGoal: "Mobile Developer", company: "Swiggy", seniority: "mid", requiredSkills: ["Swift", "iOS", "SwiftUI", "UIKit", "REST APIs", "Git", "App Architecture"], niceToHaveSkills: ["Kotlin", "React Native", "GraphQL", "Objective-C", "Testing", "App Store"], salary: "₹16-30 LPA", location: "Bengaluru" } },
	{ title: "React Native Engineer at CRED", content: "Build the CRED mobile app using React Native. Work on performance optimization, animations, and cross-platform features for premium users.", metadata: { careerGoal: "Mobile Developer", company: "CRED", seniority: "mid", requiredSkills: ["TypeScript", "React Native", "React", "JavaScript", "REST APIs", "Git", "Mobile Architecture"], niceToHaveSkills: ["Swift", "Kotlin", "GraphQL", "Testing", "Performance Optimization", "App Store"], salary: "₹14-28 LPA", location: "Bengaluru" } },
	{ title: "Junior iOS Developer at Paytm", content: "Build and maintain iOS features for India's largest payments app. Work with senior engineers on SwiftUI adoption and user experience improvements.", metadata: { careerGoal: "Mobile Developer", company: "Paytm", seniority: "junior", requiredSkills: ["Swift", "iOS", "UIKit", "SwiftUI", "REST APIs", "Git"], niceToHaveSkills: ["Kotlin", "React Native", "Testing", "App Architecture", "Firebase"], salary: "₹6-12 LPA", location: "Noida" } },
	{ title: "Flutter Developer at BharatPe", content: "Build the merchant app using Flutter. Work on cross-platform features, payment integrations, and rural-first UX design for Indian small businesses.", metadata: { careerGoal: "Mobile Developer", company: "BharatPe", seniority: "mid", requiredSkills: ["Dart", "Flutter", "REST APIs", "Git", "Mobile Architecture", "Testing", "Firebase"], niceToHaveSkills: ["Swift", "Kotlin", "React Native", "GraphQL", "Performance Optimization", "Play Store"], salary: "₹10-22 LPA", location: "Delhi" } },
	{ title: "Mobile Platform Engineer at Ola", content: "Build the mobile platform powering Ola's rider and driver apps. Work on both iOS and Android with native and cross-platform technologies.", metadata: { careerGoal: "Mobile Developer", company: "Ola", seniority: "senior", requiredSkills: ["Swift", "Kotlin", "iOS", "Android", "REST APIs", "Mobile Architecture", "System Design"], niceToHaveSkills: ["Flutter", "React Native", "GraphQL", "Performance Optimization", "CI/CD", "Testing"], salary: "₹28-50 LPA", location: "Bengaluru" } },

	// ===== Data Scientist =====
	{ title: "Data Scientist at Swiggy", content: "Build recommendation models for food discovery and delivery optimization. Design A/B tests, build statistical models, and drive product decisions.", metadata: { careerGoal: "Data Scientist", company: "Swiggy", seniority: "mid", requiredSkills: ["Statistics", "Python", "SQL", "A/B Testing", "Experimental Design", "Machine Learning", "Data Visualization"], niceToHaveSkills: ["R", "Causal Inference", "Scikit-learn", "Spark", "TensorFlow", "PyTorch"], salary: "₹16-30 LPA", location: "Bengaluru" } },
	{ title: "Data Scientist at Flipkart", content: "Build pricing, recommendation, and demand forecasting models. Run experiments and provide causal inference for product changes at e-commerce scale.", metadata: { careerGoal: "Data Scientist", company: "Flipkart", seniority: "mid", requiredSkills: ["Statistics", "Python", "SQL", "Experimental Design", "A/B Testing", "Machine Learning", "Causal Inference"], niceToHaveSkills: ["R", "Scikit-learn", "Spark", "TensorFlow", "PyTorch", "Data Visualization"], salary: "₹18-35 LPA", location: "Bengaluru" } },
	{ title: "Data Scientist at Ola", content: "Model marketplace dynamics, pricing, and demand forecasting using causal inference and econometrics. Build simulations to predict policy impact.", metadata: { careerGoal: "Data Scientist", company: "Ola", seniority: "senior", requiredSkills: ["Statistics", "Causal Inference", "Econometrics", "Python", "SQL", "Experimental Design", "Machine Learning"], niceToHaveSkills: ["R", "Spark", "Scikit-learn", "Time Series", "Deep Learning", "TensorFlow"], salary: "₹25-50 LPA", location: "Bengaluru" } },
	{ title: "Junior Data Scientist at Mu Sigma", content: "Work with decision scientists to build analytical solutions for Fortune 500 clients. Learn statistical modeling, ML, and data storytelling.", metadata: { careerGoal: "Data Scientist", company: "Mu Sigma", seniority: "junior", requiredSkills: ["Statistics", "Python", "SQL", "Machine Learning Basics", "Data Visualization", "Communication"], niceToHaveSkills: ["R", "Scikit-learn", "TensorFlow", "Tableau", "A/B Testing"], salary: "₹5-10 LPA", location: "Bengaluru" } },
	{ title: "Data Scientist at Zomato", content: "Build recommendation and personalization systems for restaurant discovery and food delivery. Analyze user behavior and improve discovery algorithms.", metadata: { careerGoal: "Data Scientist", company: "Zomato", seniority: "mid", requiredSkills: ["Statistics", "Python", "SQL", "A/B Testing", "Experimental Design", "Machine Learning", "Recommendation Systems"], niceToHaveSkills: ["R", "TensorFlow", "Scikit-learn", "Spark", "Causal Inference", "NLP"], salary: "₹16-30 LPA", location: "Gurugram" } },
	{ title: "Research Scientist at Microsoft Research India", content: "Push boundaries of AI research. Design experiments, develop novel ML architectures, and publish papers. Strong statistics and ML fundamentals.", metadata: { careerGoal: "Data Scientist", company: "Microsoft Research India", seniority: "senior", requiredSkills: ["Statistics", "Machine Learning", "Deep Learning", "Python", "PyTorch", "Research", "Experimental Design"], niceToHaveSkills: ["TensorFlow", "JAX", "Causal Inference", "Reinforcement Learning", "NLP", "Computer Vision"], salary: "₹40-80 LPA", location: "Bengaluru" } },

	// ===== Site Reliability Engineer (SRE) =====
	{ title: "SRE at Flipkart", content: "Keep Flipkart's e-commerce platform running reliably during Big Billion Days and peak traffic. Set SLOs, manage incidents, and drive reliability improvements.", metadata: { careerGoal: "Site Reliability Engineer (SRE)", company: "Flipkart", seniority: "mid", requiredSkills: ["Linux", "Scripting", "Monitoring", "Incident Response", "Automation", "Kubernetes", "Reliability Engineering"], niceToHaveSkills: ["Go", "Python", "Prometheus", "Grafana", "Docker", "Chaos Engineering"], salary: "₹18-35 LPA", location: "Bengaluru" } },
	{ title: "SRE at Swiggy", content: "Ensure Swiggy's delivery platform is reliable during peak hours. Build monitoring, automate incident response, and manage Kubernetes infrastructure.", metadata: { careerGoal: "Site Reliability Engineer (SRE)", company: "Swiggy", seniority: "mid", requiredSkills: ["Linux", "Scripting", "Monitoring", "Incident Response", "Kubernetes", "Automation", "Reliability Engineering"], niceToHaveSkills: ["Go", "Python", "Prometheus", "Grafana", "Docker", "Terraform"], salary: "₹18-32 LPA", location: "Bengaluru" } },
	{ title: "SRE at Razorpay", content: "Keep payment infrastructure running 24/7. Manage incident response, automate operations, and build reliability into the platform from day one.", metadata: { careerGoal: "Site Reliability Engineer (SRE)", company: "Razorpay", seniority: "senior", requiredSkills: ["Linux", "Monitoring", "Incident Response", "Kubernetes", "Automation", "System Design", "Reliability Engineering"], niceToHaveSkills: ["Go", "Python", "Prometheus", "Grafana", "Terraform", "Distributed Systems"], salary: "₹28-50 LPA", location: "Bengaluru" } },
	{ title: "Junior SRE at Postman", content: "Join the infrastructure team maintaining Postman's API platform. Learn reliability practices, incident response, and monitoring from senior engineers.", metadata: { careerGoal: "Site Reliability Engineer (SRE)", company: "Postman", seniority: "junior", requiredSkills: ["Linux", "Scripting", "Monitoring", "Automation", "Git", "Basic Networking"], niceToHaveSkills: ["Go", "Python", "Docker", "Kubernetes", "Prometheus", "Grafana"], salary: "₹6-12 LPA", location: "Bengaluru" } },
	{ title: "SRE at Ola", content: "Keep Ola's mobility platform running reliably. Manage ride-hailing infrastructure, real-time tracking systems, and EV fleet operations.", metadata: { careerGoal: "Site Reliability Engineer (SRE)", company: "Ola", seniority: "mid", requiredSkills: ["Linux", "Monitoring", "Incident Response", "Kubernetes", "Automation", "Scripting", "Reliability Engineering"], niceToHaveSkills: ["Go", "Python", "Prometheus", "Grafana", "Terraform", "Docker"], salary: "₹16-30 LPA", location: "Bengaluru" } },
	{ title: "SRE at Dream11", content: "Keep the fantasy sports platform running during IPL and match days. Handle massive traffic spikes and ensure low-latency user experience.", metadata: { careerGoal: "Site Reliability Engineer (SRE)", company: "Dream11", seniority: "senior", requiredSkills: ["Linux", "Monitoring", "Incident Response", "Kubernetes", "Automation", "Reliability Engineering", "System Design"], niceToHaveSkills: ["Go", "Python", "Prometheus", "Grafana", "Terraform", "Chaos Engineering"], salary: "₹25-48 LPA", location: "Mumbai" } },

	// ===== UI/UX Designer =====
	{ title: "Product Designer at CRED", content: "Design premium user experiences for credit-card users. Work on visual design, interaction design, and design systems for the CRED app.", metadata: { careerGoal: "UI/UX Designer", company: "CRED", seniority: "mid", requiredSkills: ["Figma", "User Research", "Wireframing", "Prototyping", "Visual Design", "Design Systems", "Interaction Design"], niceToHaveSkills: ["Accessibility", "User Testing", "Motion Design", "Illustration", "C4D"], salary: "₹15-28 LPA", location: "Bengaluru" } },
	{ title: "UX Designer at Flipkart", content: "Design e-commerce experiences for millions of Indian users. Conduct user research, create wireframes, and collaborate with engineering teams.", metadata: { careerGoal: "UI/UX Designer", company: "Flipkart", seniority: "mid", requiredSkills: ["Figma", "User Research", "Wireframing", "Prototyping", "Visual Design", "Design Systems", "Information Architecture"], niceToHaveSkills: ["Accessibility", "User Testing", "Interaction Design", "HTML/CSS", "Illustration"], salary: "₹14-26 LPA", location: "Bengaluru" } },
	{ title: "Senior Product Designer at Swiggy", content: "Lead design for Swiggy's food delivery and quick commerce products. Own complex features from research to launch with cross-functional teams.", metadata: { careerGoal: "UI/UX Designer", company: "Swiggy", seniority: "senior", requiredSkills: ["Figma", "User Research", "Prototyping", "Visual Design", "Design Systems", "Interaction Design", "User Testing"], niceToHaveSkills: ["Accessibility", "Motion Design", "Illustration", "HTML/CSS", "UX Strategy", "C4D"], salary: "₹25-45 LPA", location: "Bengaluru" } },
	{ title: "Junior UX Designer at Meesho", content: "Help design social commerce experiences for Bharat. Create wireframes, conduct user tests, and learn from senior designers on real products.", metadata: { careerGoal: "UI/UX Designer", company: "Meesho", seniority: "junior", requiredSkills: ["Figma", "User Research", "Wireframing", "Prototyping", "Visual Design", "Design Systems"], niceToHaveSkills: ["Interaction Design", "Accessibility", "User Testing", "Illustration", "HTML/CSS"], salary: "₹4-8 LPA", location: "Bengaluru" } },
	{ title: "UI Designer at Razorpay", content: "Design the payment platform's user interface for businesses and consumers. Work on complex financial workflows, dashboards, and design system components.", metadata: { careerGoal: "UI/UX Designer", company: "Razorpay", seniority: "mid", requiredSkills: ["Figma", "Visual Design", "Design Systems", "Prototyping", "User Research", "Wireframing", "Information Architecture"], niceToHaveSkills: ["Interaction Design", "Accessibility", "User Testing", "Illustration", "Motion Design"], salary: "₹12-24 LPA", location: "Bengaluru" } },
	{ title: "Design Systems Designer at Zomato", content: "Design and maintain Zomato's design system. Create reusable components, document patterns, and ensure visual consistency across all products.", metadata: { careerGoal: "UI/UX Designer", company: "Zomato", seniority: "mid", requiredSkills: ["Figma", "Design Systems", "Visual Design", "User Research", "Prototyping", "Wireframing", "Documentation"], niceToHaveSkills: ["Accessibility", "HTML/CSS", "Storybook", "Interaction Design", "Illustration"], salary: "₹12-24 LPA", location: "Gurugram" } },

	// ===== Product Manager =====
	{ title: "APM at Flipkart", content: "Flipkart Product Manager Program for early-career PMs. Rotate through product teams, learn product management from experienced mentors.", metadata: { careerGoal: "Product Manager", company: "Flipkart", seniority: "junior", requiredSkills: ["Product Strategy", "User Stories", "Data Analysis", "Market Research", "A/B Testing", "Communication", "Problem Solving"], niceToHaveSkills: ["SQL", "Amplitude", "Figma", "Jira", "Technical Architecture"], salary: "₹18-25 LPA", location: "Bengaluru" } },
	{ title: "Product Manager at CRED", content: "Define product strategy for CRED's premium credit-card platform. Work with engineering and design to ship features for high-value users.", metadata: { careerGoal: "Product Manager", company: "CRED", seniority: "mid", requiredSkills: ["Product Strategy", "User Stories", "Roadmapping", "A/B Testing", "Data Analysis", "Stakeholder Management", "Market Research"], niceToHaveSkills: ["SQL", "Amplitude", "Mixpanel", "Figma", "User Research", "Technical Architecture"], salary: "₹30-55 LPA", location: "Bengaluru" } },
	{ title: "Product Manager at Zomato", content: "Drive product direction for Zomato's food delivery marketplace. Define features, run experiments, and improve metrics for millions of users.", metadata: { careerGoal: "Product Manager", company: "Zomato", seniority: "mid", requiredSkills: ["Product Strategy", "User Stories", "Roadmapping", "A/B Testing", "Data Analysis", "Stakeholder Management", "Market Research"], niceToHaveSkills: ["SQL", "Amplitude", "Mixpanel", "Figma", "User Research", "Technical Architecture"], salary: "₹25-50 LPA", location: "Gurugram" } },
	{ title: "Senior PM at Swiggy", content: "Lead product strategy for Swiggy's core delivery experience. Drive experiments, analyze user behavior, and coordinate cross-team execution.", metadata: { careerGoal: "Product Manager", company: "Swiggy", seniority: "senior", requiredSkills: ["Product Strategy", "User Research", "Data Analysis", "Roadmapping", "A/B Testing", "Stakeholder Management", "Leadership"], niceToHaveSkills: ["SQL", "Amplitude", "Mixpanel", "Figma", "Technical Architecture", "Pricing Strategy"], salary: "₹40-75 LPA", location: "Bengaluru" } },
	{ title: "Product Manager at Razorpay", content: "Define product strategy for payment APIs used by millions of businesses. Work on developer experience, payment flows, and merchant dashboard.", metadata: { careerGoal: "Product Manager", company: "Razorpay", seniority: "mid", requiredSkills: ["Product Strategy", "User Stories", "Data Analysis", "API Design", "Stakeholder Management", "A/B Testing", "Market Research"], niceToHaveSkills: ["SQL", "Technical Architecture", "Amplitude", "Figma", "User Research", "Developer Experience"], salary: "₹28-52 LPA", location: "Bengaluru" } },
	{ title: "Product Manager at Ola", content: "Drive product strategy for Ola's mobility platform. Define features for riders, drivers, and fleet management products at scale.", metadata: { careerGoal: "Product Manager", company: "Ola", seniority: "mid", requiredSkills: ["Product Strategy", "User Stories", "Roadmapping", "Data Analysis", "A/B Testing", "Stakeholder Management", "Market Research"], niceToHaveSkills: ["SQL", "Amplitude", "Mixpanel", "Figma", "User Research", "Technical Architecture"], salary: "₹25-48 LPA", location: "Bengaluru" } },

	// ===== Forward Deployed Engineer =====
	{ title: "Solutions Engineer at Razorpay", content: "Help enterprise merchants integrate Razorpay's payment APIs. Design payment architectures, troubleshoot integration issues, and build demos.", metadata: { careerGoal: "Forward Deployed Engineer", company: "Razorpay", seniority: "mid", requiredSkills: ["Full-Stack Development", "API Integration", "Deployment", "Scripting", "Problem Solving", "Client Communication", "SQL"], niceToHaveSkills: ["Python", "TypeScript", "Docker", "CI/CD", "Terraform", "Monitoring"], salary: "₹12-24 LPA", location: "Bengaluru" } },
	{ title: "Customer Engineer at Google Cloud India", content: "Help enterprise customers adopt Google Cloud. Design solutions, build prototypes, and support customers through their cloud journey.", metadata: { careerGoal: "Forward Deployed Engineer", company: "Google Cloud India", seniority: "mid", requiredSkills: ["Full-Stack Development", "Cloud Architecture", "API Integration", "Deployment", "Problem Solving", "Client Communication", "Scripting"], niceToHaveSkills: ["Python", "TypeScript", "GCP", "Docker", "Terraform", "CI/CD"], salary: "₹20-40 LPA", location: "Bengaluru" } },
	{ title: "Solutions Architect at Freshworks", content: "Help global customers implement Freshworks products. Design integrations, build custom solutions, and ensure successful deployments.", metadata: { careerGoal: "Forward Deployed Engineer", company: "Freshworks", seniority: "mid", requiredSkills: ["Full-Stack Development", "API Integration", "Deployment", "Problem Solving", "Client Communication", "SQL", "Scripting"], niceToHaveSkills: ["Ruby", "TypeScript", "Docker", "CI/CD", "Cloud Platforms", "Monitoring"], salary: "₹14-28 LPA", location: "Chennai" } },
	{ title: "Junior Solutions Engineer at Postman", content: "Help enterprise customers adopt Postman's API platform. Work on integrations, demos, and customer onboarding with senior mentorship.", metadata: { careerGoal: "Forward Deployed Engineer", company: "Postman", seniority: "junior", requiredSkills: ["Full-Stack Basics", "API Integration", "Problem Solving", "Client Communication", "Git", "JavaScript"], niceToHaveSkills: ["TypeScript", "Docker", "CI/CD", "Node.js", "Postman API", "Scripting"], salary: "₹5-12 LPA", location: "Bengaluru" } },
	{ title: "Senior Solutions Architect at AWS India", content: "Design and architect solutions for AWS's largest Indian enterprise customers. Lead technical discussions, build proofs-of-concept, and drive adoption.", metadata: { careerGoal: "Forward Deployed Engineer", company: "AWS India", seniority: "senior", requiredSkills: ["Full-Stack Development", "Cloud Architecture", "System Design", "API Integration", "Client Communication", "Leadership", "Deployment"], niceToHaveSkills: ["Python", "TypeScript", "Terraform", "Docker", "Kubernetes", "CI/CD"], salary: "₹35-65 LPA", location: "Mumbai" } },
	{ title: "Technical Account Manager at Zoho", content: "Help Zoho customers implement and customize Zoho products. Build integrations, provide technical guidance, and ensure customer success.", metadata: { careerGoal: "Forward Deployed Engineer", company: "Zoho", seniority: "mid", requiredSkills: ["Full-Stack Development", "API Integration", "Deployment", "Scripting", "Problem Solving", "Client Communication", "SQL"], niceToHaveSkills: ["Java", "JavaScript", "Docker", "CI/CD", "Cloud Platforms", "Monitoring"], salary: "₹8-18 LPA", location: "Chennai" } },
];
