export const SKILL_ALIASES: Record<string, string> = {
	js: "JavaScript",
	java: "Java",
	javascript: "JavaScript",
	ts: "TypeScript",
	typescript: "TypeScript",
	py: "Python",
	python: "Python",
	cpp: "C++",
	"c++": "C++",
	"c#": "C#",
	csharp: "C#",
	".net": "C#",
	dotnet: "C#",
	golang: "Go",
	rb: "Ruby",
	rustlang: "Rust",
	postgres: "PostgreSQL",
	postgresql: "PostgreSQL",
	mongo: "MongoDB",
	mongodb: "MongoDB",
	redis: "Redis",
	docker: "Docker",
	k8s: "Kubernetes",
	kubernetes: "Kubernetes",
	aws: "AWS",
	azure: "Azure",
	gcp: "GCP",
	gcloud: "GCP",
	terraform: "Terraform",
	ansible: "Ansible",
	ng: "Angular",
	angular: "Angular",
	vuejs: "Vue",
	"nuxt.js": "Next.js",
	rest: "REST APIs",
	graphql: "GraphQL",
	jest: "Testing",
	mocha: "Testing",
	cypress: "Testing",
	playwright: "Testing",
	tdd: "Testing",
	kafka: "Kafka",
	spark: "Apache Spark",
	dbt: "Apache Spark",
	airflow: "Apache Spark",
	tableau: "Apache Spark",
	next: "Next.js",
	sql: "SQL",
	express: "Express",
	expressjs: "Express",
	"node.js": "Node",
	nodejs: "Node",
	prisma: "Prisma",
	django: "Django",
	flask: "Flask",
	spring: "Java",
	springboot: "Java",
	tailwind: "CSS",
	tailwindcss: "CSS",
	sass: "CSS",
	scss: "CSS",
	less: "CSS",
	redux: "Redux",
	"ci/cd": "CI/CD",
	cicd: "CI/CD",
	"github actions": "CI/CD",
	jenkins: "Jenkins",
	ml: "Machine Learning",
	"machine learning": "Machine Learning",
	dl: "Deep Learning",
	"deep learning": "Deep Learning",
	pytorch: "Deep Learning",
	tensorflow: "Machine Learning",
	scikitlearn: "Machine Learning",
	"scikit-learn": "Machine Learning",
	dsa: "Data Structures",
	algo: "Algorithms",
	algorithms: "Algorithms",
	leetcode: "Algorithms",
	oop: "Object-Oriented Programming",
	"object oriented": "Object-Oriented Programming",
	"design patterns": "Object-Oriented Programming",
	perf: "Performance Optimization",
	optimization: "Performance Optimization",
	security: "Network Security",
	cybersecurity: "Network Security",
	roadmap: "Career Planning",
	"full-stack": "Career Planning",
	fullstack: "Career Planning",
	"full stack": "Career Planning",
};

export function normalizeSkill(skill: string): string {
	return skill.toLowerCase().replace(/[^a-z0-9+#.]/g, "");
}

export function resolveAliases(skills: string[]): string[] {
	return skills.map((s) => {
		const key = normalizeSkill(s);
		return SKILL_ALIASES[key] || s;
	});
}
